### ISSUE TITLE
Android Push Notification with Deep Link Issue

### ISSUE THREAD

**Issue by alireza-dhp** [MORE-Platform/more-app-multiplatform#275]
Issue Summary:
Tapping on a push notification message to open an observation via a deep link does not work correctly on Android devices when the application is closed (not running in the foreground or background). Instead of opening the specific observation, the app opens the observation details page. 
Since the observation in our study is only accessible via the "Action" notification (it is a hidden observation), participants are missing the opportunity to fill out the observation.

This issue does not occur on iOS devices.

Steps to Reproduce:

- Sign in to a study with a deep link intervention.
- Close the app (ensure it is not running in the foreground or background).
- Wait till you receive a push notification.
- Tap on the push notification message from the device (not in the app) with a deep link to the observation.
- Observe that the observation details page opens instead of the observation main page.

Expected Behavior:
Tapping on the push notification message should directly open the observation, even when the app is closed.

Test Environment:
Google Pixel 3 XL
Android version: Latest (v4.0.17)
iOS: Not affected

related issue? https://github.com/MORE-Platform/more-app-multiplatform/issues/197#issuecomment-1759766411

**Comment by janoliver20** [comment]
@alireza-dhp Hi Alireza, which Android OS Version are you using?

**Comment by janoliver20** [comment]
Issue is fixed, deeplinks are now working even if the App is freshly opened

**Comment by alirezafatehi** [comment]
Thank you for addressing the issue. 
However, it still occurs when the app is first opened from an action notification right after the study resumes. 
It's not urgent, but I'll keep the issue open for the next round of bug fixes.

**Comment by alirezafatehi** [comment]
Here are screenshots from a participant who experienced the issue even after the bug was fixed. 
As a result, the participant was unable to respond to this observation.

![Image](https://github.com/user-attachments/assets/8dd0bcee-f4b3-46f1-b756-dc4598c0c853)

![Image](https://github.com/user-attachments/assets/b9f8550b-ed69-4ea2-92fb-e4d4ca10ab38)

**Comment by andresgruber** [comment]
Tested with iOS 4.0.22 and Android 4.0.22

**Comment by janoliver20** [comment]
Version 4.0.22 now available on develop since the last PR merge: https://github.com/MORE-Platform/more-app-multiplatform/pull/287
